var SKL = '<category name="%{BKY_CATEGORY_SCIKIT}" colour="%{BKY_SCIKITLEARN_HUE}">';

//<!-- 기본 - 자주쓰는 블록, 모델 학습, 예측, 평가, 임포트 등 -->';
SKL += '<category name="%{BKY_SKI_BASIC}" colour="%{BKY_SCIKITLEARN_HUE}">';
//<label text="라이브러리 임포트"></label>';
SKL += '<label text="%{BKY_SKL_LIBRARY}"></label>';

SKL += '<block type="import_scikit_learn"></block>';

//<label text="데이터 처리(핸들링)"></label>';
SKL += '<label text="%{BKY_SKL_DATA}"></label>';
SKL += '<block type="train_test_split"></block>';
//<!-- SKL += '<value name="x_data">';
//   SKL += '<block type="variables_get">';
//     SKL += '<field name="VAR">x_data</field>';
//   SKL += '</block>';
// SKL += '</value>';
// SKL += '<value name="y_data">';
//   SKL += '<block type="variables_get">';
//     SKL += '<field name="VAR">y_data</field>';
//   SKL += '</block>';
// SKL += '</value>';
// SKL += '<value name="x_train">';
//   SKL += '<block type="variables_get">';
//     SKL += '<field name="VAR">x_train</field>';
//   SKL += '</block>';
// SKL += '</value>';
// SKL += '<value name="x_test">';
//   SKL += '<block type="variables_get">';
//     SKL += '<field name="VAR">x_test</field>';
//   SKL += '</block>';
// SKL += '</value>';
// SKL += '<value name="y_train">';
//   SKL += '<block type="variables_get">';
//     SKL += '<field name="VAR">y_train</field>';
//   SKL += '</block>';
// SKL += '</value>';
// SKL += '<value name="y_test">';
//   SKL += '<block type="variables_get">';
//     SKL += '<field name="VAR">y_test</field>';
//   SKL += '</block>';
// SKL += '</value>';
// SKL += '<value name = "test_size">';
//   SKL += '<shadow type="indata">';
//     SKL += '<field name="indata1">0.2</field>';
//   SKL += '</shadow>';
// SKL += '</value>';
// SKL += '<value name = "seed">';
//   SKL += '<shadow type="indata">';
//     SKL += '<field name="indata1">0</field>';
//   SKL += '</shadow>';
// SKL += '</value>'; -->';


SKL += '<block type="labelencoder">';
SKL += '<value name="df">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR"></field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "column">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1"></field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="onehotencoder">';
SKL += '<value name="df">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR"></field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';

// SKL += '<block type="sklearn_scale">';
// SKL += '<value name = "variable">';
// SKL += '<block type="variables_get">';
// SKL += '<field name="VAR">scaled_data</field>';
// SKL += '</block>';
// SKL += '</value>';
// SKL += '<value name = "data">';
// SKL += '<shadow type="indata">';
// SKL += '<field name="indata1"></field>';
// SKL += '</shadow>';
// SKL += '</value>';
// SKL += '<value name = "axis">';
// SKL += '<shadow type="indata">';
// SKL += '<field name="indata1">0</field>';
// SKL += '</shadow>';
// SKL += '</value>';
// SKL += '</block>';

SKL += '<block type="sklearn_scale">';
SKL += '<value name = "variable">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">scaled_data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "params">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1"></field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="minmax_scalar">';
SKL += '<value name="data">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">x_data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="standard_scalar">';
SKL += '<value name="data">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">x_data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="normal">'
SKL += '<value name="Normalization_data">'
SKL +=   '<block type="variables_get">'
SKL +=     '<field name="VAR">df</field>'
SKL +=   '</block>'
SKL += '</value>'
SKL += '</block>'

//<label text="모델 학습 및 평가"></label>';
SKL += '<label text="%{BKY_SKL_TRAIN_EVA}"></label>';

SKL += '<block type="model_fit">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="X_train">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">x_train</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="Y_train">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_train</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="fit_predict">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="x_train">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">x_train</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="model_score">';
SKL += '<value name="model_name">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="x_test">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">x_test</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="y_test">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_test</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';
SKL += '<block type="model_predict">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="NAME">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">x_test</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';

//<label text="속성 추출"></label>';
SKL += '<label text="%{BKY_SKL_ATTRI_EXT}"></label>';

SKL += '<block type="coef">';
SKL += '<value name="coef">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';
SKL += '<block type="intercept">';
SKL += '<value name="intercept">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';

SKL += '</category>';

SKL += '<category name="%{BKY_SKI_DATA}" colour="%{BKY_SCIKITLEARN_HUE}">';
//<label text="데이터셋"></label>';
SKL += '<label text="%{BKY_SKL_DATA_SET}"></label>';

SKL += '<block type="import_dataset">';
SKL += '<value name="x_data">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">x_data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="y_data">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="import_load_digits">';
SKL += '<value name="x_data">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">x_data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="y_data">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "n_class">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">10</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="random_import_blobs">';
SKL += '<value name="x_data">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">x_data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="y_data">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "sa">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">100</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "fe">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">2</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "seed">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="random_import_moons">';
SKL += '<value name="x_data">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">x_data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="y_data">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "sa">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">100</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "noise">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">None</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "seed">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="make_circles">';
SKL += '<value name="x_data">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">x_data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="y_data">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "n_samples">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">100</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "factor">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0.5</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

//<label text="데이터 핸들링"></label>';
SKL += '<label text="%{BKY_SKL_DATA_HANDLING}"></label>';

SKL += '<block type="train_test_split"></block>';
//<!-- SKL += '<value name="x_data">';
//   SKL += '<block type="variables_get">';
//     SKL += '<field name="VAR">x_data</field>';
//   SKL += '</block>';
// SKL += '</value>';

// SKL += '<value name="y_data">';
//   SKL += '<block type="variables_get">';
//     SKL += '<field name="VAR">y_data</field>';
//   SKL += '</block>';
// SKL += '</value>';
// SKL += '<value name="x_train">';
//   SKL += '<block type="variables_get">';
//     SKL += '<field name="VAR">x_train</field>';
//   SKL += '</block>';
// SKL += '</value>';
// SKL += '<value name="x_test">';
//   SKL += '<block type="variables_get">';
//     SKL += '<field name="VAR">x_test</field>';
//   SKL += '</block>';
// SKL += '</value>';
// SKL += '<value name="y_train">';
//   SKL += '<block type="variables_get">';
//     SKL += '<field name="VAR">y_train</field>';
//   SKL += '</block>';
// SKL += '</value>';
// SKL += '<value name="y_test">';
//   SKL += '<block type="variables_get">';
//     SKL += '<field name="VAR">y_test</field>';
//   SKL += '</block>';
// SKL += '</value>';
// SKL += '<value name = "test_size">';
//   SKL += '<shadow type="indata">';
//     SKL += '<field name="indata1">0.2</field>';
//   SKL += '</shadow>';
// SKL += '</value>';
// SKL += '<value name = "seed">';
//   SKL += '<shadow type="indata">';
//     SKL += '<field name="indata1">0</field>';
//   SKL += '</shadow>';
// SKL += '</value>'; -->';

SKL += '<block type="labelencoder">';
SKL += '<value name="df">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR"></field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "column">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1"></field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="onehotencoder">';
SKL += '<value name="df">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR"></field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';

// SKL += '<block type="sklearn_scale">';
// SKL += '<value name = "variable">';
// SKL += '<block type="variables_get">';
// SKL += '<field name="VAR">scaled_data</field>';
// SKL += '</block>';
// SKL += '</value>';
// SKL += '<value name = "data">';
// SKL += '<shadow type="indata">';
// SKL += '<field name="indata1"></field>';
// SKL += '</shadow>';
// SKL += '</value>';
// SKL += '<value name = "axis">';
// SKL += '<shadow type="indata">';
// SKL += '<field name="indata1">0</field>';
// SKL += '</shadow>';
// SKL += '</value>';
// SKL += '</block>';

SKL += '<block type="sklearn_scale">';
SKL += '<value name = "variable">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">scaled_data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "params">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1"></field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="minmax_scalar">';
SKL += '<value name="data">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">x_data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="standard_scalar">';
SKL += '<value name="data">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">x_data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="normal">'
SKL += '<value name="Normalization_data">'
SKL +=   '<block type="variables_get">'
SKL +=     '<field name="VAR">df</field>'
SKL +=   '</block>'
SKL += '</value>'
SKL += '</block>'

SKL += '<block type="polynomialfeatures">';
SKL += '<value name = "NAME">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1"></field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<label text="차원 축소"></label>';

SKL += '<block type="pca">';
SKL += '<value name="data">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "n_components">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">None</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="pca_explained_variance_ratio_">';
SKL += '</block>';

SKL += '<block type="tsne">';
SKL += '<value name="data">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "n_components">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">2</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "perplexity">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">30.0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "learning_rate">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">200.0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="mds">';
SKL += '<value name="data">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "n_components">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">2</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="lle">';
SKL += '<value name="data">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "n_neighbors">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">5</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "n_components">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">2</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="isomap">';
SKL += '<value name="data">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "n_neighbors">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">5</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "n_components">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">2</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '</category>';

SKL += '<category name="%{BKY_SKI_PRE}" colour="%{BKY_SCIKITLEARN_HUE}">';
SKL += '<block type="linear_regression">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="sgd_regressor">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "numEpochs">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">100</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="ridge">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "numAlpha">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">1.0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="lasso_regression">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "alpha">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">1.0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="elasticnet_regression">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "alpha">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">1.0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "l1_ratio">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0.5</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="bayesian_ridge">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';


SKL += '<block type="adaboostregressor">';
SKL += '<value name="NAME">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "NAME2">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">100</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "NAME3">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="gradientboostingregressor">';
SKL += '<value name="NAME">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "NAME2">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">100</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="randomforestregressor">';
SKL += '<value name="NAME">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "NAME2">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">100</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "NAME3">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="kneighborsregressor_function">';
SKL += '<value name="value">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "value1">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1"></field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

// SKL += '<block type="linearsvr">';
// SKL += '<value name = "NAME">';
// SKL += '<shadow type="indata">';
// SKL += '<field name="indata1">0</field>';
// SKL += '</shadow>';
// SKL += '</value>';
// SKL += '</block>';

SKL += '<block type="svr">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "epsilon">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0.1</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "C">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">1.0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "gamma">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">"scale"</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';


SKL += '</category>';

SKL += '<category name="%{BKY_SKI_CLASSIF}" colour="%{BKY_SCIKITLEARN_HUE}">';
SKL += '<block type="logistic_regression">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "numSeed">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="logistic_regression_cv">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "numCv">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">5</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "numSeed">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

// SKL += '<block type="ridge_classifier">';
// SKL += '<value name="model">';
// SKL += '<block type="variables_get">';
// SKL += '<field name="VAR">model</field>';
// SKL += '</block>';
// SKL += '</value>';
// SKL += '</block>';

SKL += '<block type="ridge_classifier">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "alpha">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">1.0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';


SKL += '<block type="sgd_classifier">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "max_iter">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">100</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "tol">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0.001</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';


SKL += '<block type="decision">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "depth">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">10</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "seed">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="adaboostclassifier">';
SKL += '<value name="NAME">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "NAME2">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">50</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "NAME3">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="gradientboostingclassifier">';
SKL += '<value name="NAME">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "NAME2">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">100</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="random_forest_classifier">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "n_estimators">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">100</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "max_depth">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">None</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="kneighborsclassifier_function">';
SKL += '<value name="value">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "value1">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">5</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

// SKL += '<block type="linearsvc">';
// SKL += '<value name = "NAME">';
// SKL += '<shadow type="indata">';
// SKL += '<field name="indata1">0</field>';
// SKL += '</shadow>';
// SKL += '</value>';
// SKL += '</block>';

SKL += '<block type="svc">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "C">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">1.0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "gamma">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">"scale"</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="stacking_classifier">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "estimators">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1"></field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "final_estimator">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1"></field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="voting_classifier">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "estimator">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1"></field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="bagging_classifier">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "base_estimator">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1"></field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "n_estimators">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">10</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "max_samples">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">1.0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

// 트리구조출력 - plot_tree
SKL += '<block type="plottree">';
SKL += '<value name="option">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1"></field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

// 그리드 검색
SKL += '<block type="GridSearchCV">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">gs</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="option">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">sklearn.tree.DecisionTreeClassifier(random_state=42), params, n_jobs=-1</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';


// 랜덤검색
SKL += '<block type="RandomizedSearchCV">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">gs</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="option">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">sklearn.tree.DecisionTreeClassifier(random_state=42), params, n_iter=100, n_jobs=-1, random_state=42</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

// 엑스트라 트리
SKL += '<block type="ExtraTreesClassifier">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">et</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="option">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">n_jobs=-1, random_state=42</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '</category>';

SKL += '<category name="%{BKY_SKI_CLUSTER}" colour="%{BKY_SCIKITLEARN_HUE}">';
SKL += '<block type="k_means">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "cnt">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">2</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="dbscan">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "eps">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0.5</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "min_samples">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">5</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="agglomerative_clustering">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "n_clusters">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">2</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="isolation_forest">';
SKL += '<value name="Isolation_Forest_val">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "Isolation_Forest_estimators">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">100</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "Isolation_Forest_connection">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0.5</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "Isolation_Forest_randomstate">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="one_class_svm">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "degree">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">3</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "gamma">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">"scale"</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="local_outlier_factor">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "n_neighbors">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">20</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

//<label text="K-Means 속성 추출"></label>';
SKL += '<label text="%{BKY_SKL_K_MEANS}"></label>';

SKL += '<block type="k_means_inertia">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="k_means_centroid">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';

SKL += '</category>';

SKL += '<category name="%{BKY_SKI_EVA}" colour="%{BKY_SCIKITLEARN_HUE}">';

//<label text="기본 평가 지표"></label>';
SKL += '<label text="%{BKY_SKL_BASIC_EVA}"></label>';

SKL += '<block type="acc_score">';
SKL += '<value name="yt">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_test</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="yp">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_pred</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';
SKL += '<block type="mae">';
SKL += '<value name="yt">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_test</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="yp">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_pred</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';
SKL += '<block type="mse">';
SKL += '<value name="yt">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_test</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="yp">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_pred</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';

//<label text="고급 평가 지표"></label>';
SKL += '<label text="%{BKY_SKL_ADV}"></label>';
//<!-- SKL += '<block type="AUC">';
//   SKL += '<value name="yt">';
//     SKL += '<block type="variables_get">';
//       SKL += '<field name="VAR">x_data</field>';
//     SKL += '</block>';
//   SKL += '</value>';
//   SKL += '<value name="yp">';
//     SKL += '<block type="variables_get">';
//       SKL += '<field name="VAR">y_pred</field>';
//     SKL += '</block>';
//   SKL += '</value>';
// SKL += '</block>'; -->';
SKL += '<block type="AP">';
SKL += '<value name="yt">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_test</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="yp">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_score</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';
SKL += '<block type="precision">';
SKL += '<value name="yt">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_test</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="yp">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_pred</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';
SKL += '<block type="median">';
SKL += '<value name="yt">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_test</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="yp">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_pred</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="sivalidation">';
SKL += '<value name="variable">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">var</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="em">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="x">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">x_data</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name="y">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">y_data</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name="cv">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">None</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="silhouette_score">';
SKL += '<value name="x">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">x_data</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="labels">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_pred</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="classification_report">';
SKL += '<value name="classification_report_Y_true">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_test</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="classification_report_y_pred">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">y_pred</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';
//<label text="유사도"></label>';
SKL += '<label text="%{BKY_SKL_SIM}"></label>';
//<!-- 코사인 유사성 -->';
SKL += '<block type="cosine_similarity">';
SKL += '<value name="input_x">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">x</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name="input_y">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">y</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';
//<!-- 코사인 길이 -->';
SKL += '<block type="cosine_distance">';
SKL += '<value name="input_x">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">x</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name="input_y">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">y</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';
//<!-- 벡터쌍 거리행렬 -->';
SKL += '<block type="euclidean_distances">';
SKL += '<value name="input_x">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">x</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name="input_y">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">y</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';
//<!-- 벡터사이 L1길이 -->';
SKL += '<block type="manhattan_distances">';
SKL += '<value name="input_x">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">x</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name="input_y">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">y</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';
SKL += '</category>';

SKL += '<category name="교차검증" colour="%{BKY_SCIKITLEARN_HUE}">';

SKL += '<label text="생성"></label>';

SKL += '<block type="sivalidation">';
SKL += '<value name="variable">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">var</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="em">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="x">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">x_data</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name="y">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">y_data</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name="cv">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">None</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="kfold_create">';
SKL += '<value name="variable">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">kfold</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="n_splits">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">2</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="stratified_kfold_create">';
SKL += '<value name="variable">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">kfold</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="n_splits">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">2</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="group_kfold_create">';
SKL += '<value name="variable">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">group_kfold</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="n_splits">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">5</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';


SKL += '<block type="loo_create">';
SKL += '<value name="variable">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">loo</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="shuffle_split_create">';
SKL += '<value name="variable">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">rs</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name="n_splits">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">10</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name="test_size">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">None</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<label text="메소드"></label>';

SKL += '<block type="cv_get_n_splits">';
SKL += '<value name="variable">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1"></field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name="X">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1"></field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name="y">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1"></field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name="groups">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1"></field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="cv_split">';
SKL += '<value name="variable">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1"></field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name="X">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1"></field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name="y">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1"></field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name="groups">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1"></field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '</category>';

//<!-- 계수, 절편 추출 등 -->';
SKL += '<category name="%{BKY_SKI_NEURAL}" colour="%{BKY_SCIKITLEARN_HUE}">';
SKL += '<block type="perceptron">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "numSeed">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="sklearn_mlp_regressor">';
SKL += '<value name="sklearn_mlp_lib_val">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "sklearn_mlp_hidden_layer_sizes">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">64, 32</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "sklearn_MLP_Max_iter">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">100</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "sklearn_MLP_random_state">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "sklearn_MLP_batch_size">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">32</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "sklearn_MLP_learning_rate">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0.001</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "alpha">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0.0001</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="sklearn_mlp_classifier">';
SKL += '<value name="sklearn_mlp_lib_val">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "sklearn_mlp_hidden_layer_sizes">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">64, 32</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "sklearn_MLP_Max_iter">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">100</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "sklearn_MLP_random_state">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "sklearn_MLP_batch_size">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">32</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "sklearn_MLP_learning_rate">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0.001</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "alpha">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0.0001</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';

SKL += '<block type="bernoullirbm">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '<value name = "hi">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">50</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "lr">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0.001</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "batch">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">16</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "epochs">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">100</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '<value name = "seed">';
SKL += '<shadow type="indata">';
SKL += '<field name="indata1">0</field>';
SKL += '</shadow>';
SKL += '</value>';
SKL += '</block>';
SKL += '<block type="mlp_loss">';
SKL += '<value name="model">';
SKL += '<block type="variables_get">';
SKL += '<field name="VAR">model</field>';
SKL += '</block>';
SKL += '</value>';
SKL += '</block>';
//<!-- 기존에 남은 블록들입니다. 처리하던가, 새로 추가하던가 해야할 듯. -- 2021-01-26 작성 -->';
//<!-- //<label text="남은 블록(Deprecated.)"></label>';
// SKL += '<block type="normal">';
//   SKL += '<value name="Normalization_data">';
//     SKL += '<block type="variables_get">';
//       SKL += '<field name="VAR"></field>';
//     SKL += '</block>';
//   SKL += '</value>';
// SKL += '</block>';
// SKL += '<block type="fetch_openml"></block>';        
// SKL += '<block type="kneighborstransformer_function"></block>';
// SKL += '<block type="kneighbors_graph_function"></block>';
// SKL += '<block type="tree_text"></block>'; 
// SKL += '<block type="metrics_fit_predict"></block>'; -->';
//<!-- SKL += '<block type="normal">';
//   SKL += '<value name="Normalization_data">';
//     SKL += '<block type="variables_get">';
//       SKL += '<field name="VAR"></field>';
//     SKL += '</block>';
//   SKL += '</value>';
// SKL += '</block>'; -->';

SKL += '</category>';

SKL += '</category>';
